# Logging
verbose=true

# Audio device
dev=default
input=true
output=true
rate=44100

# KISS over TCP
tcp-kiss=8144

# TNC2 (and extras) over TCP
tcp-tnc2=8145

# TNC2 over UDP
udp-tnc2-addr=127.0.0.1
udp-tnc2-port=18144
udp-tnc2-listen=28144

# KISS over UDS
uds-kiss=/tmp/mw_kiss.sock

# Others
tnc2-extras=true